# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    search_weights:
        entities:
            vehicule: 1.0
            chauffeur: 0.9
            voyage: 0.8
            document: 0.7
            affectation: 0.7
            reparation: 0.6
        matches:
            exact: 1.0
            beginning: 0.8
            partial: 0.6
            fuzzy: 0.4

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventSubscriber\RegionSubscriber:
        tags:
            - { name: kernel.event_subscriber }
    App\Service\NotificationService:
        arguments:
            $documentRepository: '@App\Repository\DocumentVehiculeRepository'
            $vidangeRepository: '@App\Repository\VidangeVehiculeRepository'
            $voyageRepository: '@App\Repository\VoyageRepository'
            $vehiculeRepository: '@App\Repository\VehiculeRepository'
            $router: '@router'
    App\EventListener\AccessDeniedListener:
        arguments:
            $router: '@router'
            $requestStack: '@request_stack'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    App\EventListener\LoginListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    App\Service\AuditLogger:
        arguments:
            $em: '@doctrine.orm.entity_manager'
            $security: '@security.helper'
